version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch_haiyi
    hostname: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2000m -Xmx2000m"
    restart: always
#    volumes:
#      - ~/data/elasticsearch/data:/var/data/elasticsearch
#      - ~/data/elasticsearch/log:/var/log/elasticsearch